// workshop-exercises/01-beyond-paradigms/react/src/App.tsx
import React from "react";
import { OrderService } from "./components/OrderService";

// =============================================================================
// DEMONSTRATION: Four Pillars of OOP in React + TypeScript
// =============================================================================

const App: React.FC = () => {
  return (
    <div>
      <h1>React + TypeScript OOP Demo</h1>
      <OrderService />
    </div>
  );
};

export default App;

// workshop-exercises/01-beyond-paradigms/angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { OrderComponent } from "./components/order.component";

// =============================================================================
// DEMONSTRATION: Four Pillars of OOP in Angular (Service-Based + Component Paradigm)
// =============================================================================

@Component({
  selector: "app-root",
  standalone: true,
  imports: [OrderComponent],
  template: `
    <div>
      <h1>Angular + TypeScript OOP Demo</h1>
      <app-order></app-order>
    </div>
  `,
})
export class AppComponent {
  title = "Angular OOP Demo";
}
